export enum RecordTypeEnum {
  A = 'A',
  AAAA = 'AAAA',
  CAA = 'CAA',
  CERT = 'CERT',
  CNAME = 'CNAME',
  DNSKEY = 'DNSKEY',
  DS = 'DS',
  HTTPS = 'HTTPS',
  LOC = 'LOC',
  MX = 'MX',
  NAPTR = 'NAPTR',
  NS = 'NS',
  PTR = 'PTR',
  SMIMEA = 'SMIMEA',
  SRV = 'SRV',
  SSHFP = 'SSHFP',
  SVCB = 'SVCB',
  TLSA = 'TLSA',
  TXT = 'TXT',
  URI = 'URI',
}
